### ISSUE TITLE
trang study đã fix lại

### ISSUE THREAD

**Issue by cuongdz** [LetterC67/Cheat-study.hanoi.edu.vn#11]
code wronganswer không nhập dc nữa

**Comment by cuongdz** [comment]
code đáp án đúng cũng ko nhập dc nữa

**Comment by cuongdz** [comment]
mọi người cần sự giúp đỡ của anh đó admin hãy sử dụng bộ não siêu thông minh của anh được ko? chúng ta cần code hack mới :)

**Comment by hung11111** [comment]
anh ơi sửa code đi chúng e rất cần a

**Comment by cuongdz** [comment]
Bây giờ các bạn có thể làm xong 1 đề và ấn chi tiết làm bài thì sex hiện đáp án đúng nha mọi ngừi
