### ISSUE TITLE
AD ơi em khối 9 e dùng code gắn vào console không được

### ISSUE THREAD

**Issue by xx1stxx** [LetterC67/Cheat-study.hanoi.edu.vn#15]

**Comment by xx1stxx** [comment]
phần hướng dẫn ở đâu hả ad

**Comment by xx1stxx** [comment]
e khối 9 e vào phần console paster cái mới của ad tự điền kết quả mà không dc

**Comment by LetterC67** [comment]
hướng dẫn chi tiết ở phần II/-1 nhé bạn!
Như trong hướng dẫn thì bạn phải chạy code lấy đáp án trươc khi chạy code auto
