### ISSUE TITLE
có thể là 1 thứ để sửa :D

### ISSUE THREAD

**Issue by gitgud135** [LetterC67/Cheat-study.hanoi.edu.vn#16]
mình dùng thử code thì thấy rằng phải được 0 điểm thì code mới dùng được. tức là nếu điểm chỉ cần cao hơn 0 thì bước đầu dùng code getcorrectans sẽ bị lỗi

**Comment by LetterC67** [comment]
Cảm ơn bạn! Mình đã sửa lại rồi nhé!
