### ISSUE TITLE
Một bug nho nhỏ nữa.

### ISSUE THREAD

**Issue by ND-268** [LetterC67/Cheat-study.hanoi.edu.vn#17]
Một vài câu có đáp án là hình ảnh thì lại bị bug, và có những đề như là hóa hk1 đề 2 lớp 9 có câu k hiện đáp án thì k chọn tự động ạ ;v
![image](https://user-images.githubusercontent.com/63328043/78772796-80cdb980-79bc-11ea-9825-ba1ef2664f7a.png)
![image](https://user-images.githubusercontent.com/63328043/78772818-888d5e00-79bc-11ea-8f1e-c298b91813dc.png)
Mong admin sớm khắc phục ạ.

**Comment by LetterC67** [comment]
Mình đã sửa phần đáp án là ảnh rồi nhé!
