### ISSUE TITLE
Xuống dòng

### ISSUE THREAD

**Issue by kii7061** [LetterC67/Cheat-study.hanoi.edu.vn#19]
Cái code get correct mới nhất update hqua ấy sao đến lúc mình gõ code ấn enter nó lại xuống dòng nhỉ mà kp undifined.
https://github.com/LetterC67/Cheat-study.hanoi.edu.vn/commit/4f25c2ee93e6c5eebae981475f7e4ff7c76fa919

**Comment by LetterC67** [comment]
Chào bạn!
Code mới này gõ Enter vẫn là "undefined" nhé! Dù sao thì quan trọng là kết quả là code có chạy thành công không chứ bạn!
