### ISSUE TITLE
Bạn ơi mình làm theo các bước, lần đầu không cần đến lần 4 mình được 10 luôn thì làm thế nào mình lấy được đáp án nhỉ? Làm 4 lần thì nó cho đáp án nhưng không đúng. :((

### ISSUE THREAD

**Issue by gitgud135** [LetterC67/Cheat-study.hanoi.edu.vn#2]

**Comment by LetterC67** [comment]
Có một số đề thì làm được 10 luôn nhé! Như vậy bạn cần vào làm lại, lần này chỉ cần chạy code trong "cheatCode_v2.js" một lần và trước khi nộp bài, bạn chạy tiếp lệnh trong file "showAnswerKey.js" để đáp án tự động được chọn. Nếu là đề làm 1 lần 10 luôn thì không cần chạy đến lần thứ 4 nhé! 
Bạn cũng không nên quá lạm dụng sử dụng mà hãy cố gắng tự làm bài nhé!

**Comment by gitgud135** [comment]
Okey bạn. Mình muốn biết đáp án để ghi chép học thuộc thui ý mà nma lần 2 chạy nó lại cho kết quả sai :v

**Comment by LetterC67** [comment]
Bạn có thể chạy thử lệnh "localStorage.clear()" trước khi chạy lần thứ 2 nhé

**Comment by gitgud135** [comment]
mình cảm ơn bạn nha,có chút tài liệu học rùi ^^
