### ISSUE TITLE
làm thế này có bị lộ là cheating k ạ

### ISSUE THREAD

**Issue by tym111** [LetterC67/Cheat-study.hanoi.edu.vn#20]
nếu làm mấy bước này thì bài làm có bị lộ là cheating k a

**Comment by LetterC67** [comment]
Chào bạn!
Rõ ràng là không ai lại có thể làm được nhiều điểm 10 đến thế trong thời gian vài giây đến khoảng vài chục giây. Bạn có thể để lâu lâu lâu một tí rồi nộp. 
Dù sao bạn muốn không bị lộ thì dùng ít thôi nhé! Mục đích là mình muốn giúp các bạn có quá nhiều bài tập giải quyết nhanh hơn thôi!

**Comment by tym111** [comment]
ngoài vụ thời gian thì có bị lộ k ad? chứ e làm vẫn để bài cho hết giờ cho đỡ bị nghi ngờ

**Comment by LetterC67** [comment]
Ngoài việc thời gian thì một lô một lốc điểm 10 liên tục cũng có thể tạo nghi vấn. Bạn nên thử sức mình làm trước nhé!
