### ISSUE TITLE
Code một lỗi một số câu.

### ISSUE THREAD

**Issue by ND-268** [LetterC67/Cheat-study.hanoi.edu.vn#23]
Như đề Ôn tập - THCS Môn GDCD - Đề số 25 thì code một lỗi 1 câu.
đề Ôn tập THCS - Môn Tiếng Anh 9 - Đề số 25 lỗi 4 câu. Mong ad fix. Chạy code auto xong nó còn mấy câu lỗi là k chọn ạ.

**Comment by LetterC67** [comment]
Bạn đã chạy code auto.js hay auto_v2.js nhỉ?

**Comment by LetterC67** [comment]
Mình đã phát hiện ra lỗi. Mình đã sửa ở cách 2 nhưng quên sửa ở cách 1.  Bây giờ cả 2 chạy bình thường rồi nhé!
