### ISSUE TITLE
a cap nhat cac examid cho de toan lop 11 duoc k a

### ISSUE THREAD

**Issue by hoangzzz** [LetterC67/Cheat-study.hanoi.edu.vn#25]

**Comment by LetterC67** [comment]
Chào bạn!
Việc lấy được các ID này cũng đòi hỏi một khoảng kha khá thời gian nên sẽ có thể hơi lâu một chút nhưng mình sẽ cố gắng lấy trong thời gian sớm nhất. Trong lúc đó, bạn cũng có thể sử dụng cách 2 nhé!
