### ISSUE TITLE
lỗi mã đề ở examID

### ISSUE THREAD

**Issue by levinhhung20032** [LetterC67/Cheat-study.hanoi.edu.vn#43]
mã đề 705-3059 bị lỗi r nhé T.T

**Comment by LetterC67** [comment]
Cách sử dụng examID là không dùng được nữa nhé bạn!

**Comment by levinhhung20032** [comment]
Bh còn mỗi cách thủ công thôi đúng ko :v

Vào 19:18, T.7, 18 Th4, 2020 LetterC67 <notifications@github.com> đã viết:

**Comment by LetterC67** [comment]
Đúng rồi bạn!
