### ISSUE TITLE
Code mới update lỗi.

### ISSUE THREAD

**Issue by ND-268** [LetterC67/Cheat-study.hanoi.edu.vn#46]
Code gercorrect mới update lỗi dòng copyStringToClipboard(str) ở gần cuối ạ
![image](https://user-images.githubusercontent.com/63328043/79872777-6958ec80-8410-11ea-9cf0-a1fae5f02a8c.png)

**Comment by LetterC67** [comment]
Mình bất cẩn quá! Sửa lại rồi nhé bạn!

**Comment by ND-268** [comment]
ủa thế lỗi như thế sửa như nào hả bác.

**Comment by LetterC67** [comment]
Mình sửa rồi nhé bạn! Bây giờ dùng bình thường rồi
