### ISSUE TITLE
Lỗi chạy auto.js

### ISSUE THREAD

**Issue by paphananh** [LetterC67/Cheat-study.hanoi.edu.vn#53]
Console:
Uncaught SyntaxError: Unexpected token M in JSON at position 0
    at JSON.parse (<anonymous>)
    at eval (eval at <anonymous> (eval at <anonymous> (on-tap-thcs-mon-tieng-anh-9-e-so-9-293:8)), <anonymous>:1:1555)
    at eval (eval at <anonymous> (on-tap-thcs-mon-tieng-anh-9-e-so-9-293:8), <anonymous>:1:6)
    at <anonymous>:8:1

**Comment by LetterC67** [comment]
Bạn kiểm tra lại xem các thao tác có đúng không nhé! Nếu bạn dùng key có sẵn thì chú ý copy hết key vào nhé!

**Comment by paphananh** [comment]
Mình copy key hết vào rồi bạn.

**Comment by paphananh** [comment]
Key dạng ntn đúng k bạn: MarkletterA,B,CorDonyouranswersheettoindicatethebestsentencethatcanbemadefromthecuesgiven.engine/car/need/clean/once/month/.,Theengineofthecarneedscleaningonceamonth.,ReadthefollowingpassageandmarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.NewYorkiscalled“theBigApple”.Maybeitisnotexactlylikeanapple,it’scertainlyverybig.Therearetoomanypeople,that’stheproblem.Thestreetsarealwaysfullofcarsandtrucks;youcanneverfindaplacetopark.Travellingaroundisnevereasyinthecity.Ifyouhaveenoughmoney,youcantakeataxi.NewYorkcabsareyellow.Theylookallthesame.Butthedriversareverydifferent.SomewerebornandraisedinNewYork,butmanyarenewcomerstotheUnitedStates.Afewdriveslowly,butmostgoveryfast.Cabdrivingisadifficultjob.Itcanbedangerous,too.Thievesoftentrytostealthedrivers’money.Driverssometimesgethurt.Ifyoudon’twanttotakeataxi,youcangobybusoryoucantakethesubway.Thesubwayisquickandit’scheap,butsomeofitspartsareoldanddirty.Lightsdon’talwaysworkandthereareoftenfiresonthetrack.Onsomesubwaylines,therearenew,cleanandsilvertrains.Butyoucan’tseethecoloroftheoldtrainseasily.Thereistoomuchdirtandtoomuchgraffiti,insideandoutside.Youmayfindithardtosee_____.,thecoloroftheoldtrains,ReadthefollowingtextandmarktheletterA,B,CorDonyouranswertoindicatethecorrectwordthatbestfitsblank(23).Located(23)_______GiaoThuydistrict,theCountrysideMuseum(24)_______apopularattractionforvisitorstoNamDinhProvince.Themuseumwasestablishedbyaretiredteacher,Mrs.Khieu,whileworkingasateacher,sheliked(25)_______householdutensilsofresidentsintheTonkinregion.(26)_______the1990s,shehaspreservedobjectsthatpeople,particularfarmers,regularlyusedintheolddays,sothatyoungergenerationscanlearnabouttheseobjects.KnowingMrs.Khieu’sgood(27)_______,manypeoplehavebroughtherdailyusedsubjectsinruralareas,suchaswaterbuckets,differenttypesofbrooms,bronzeandwoodentraysandfishingbaskets.,in,MarkletterA,B,CorDtoindicatethewordOPPOSITEinmeaningtotheunderlinedwordineachofthefollowingquestionsComeandjoinusatourlocalfestivalthisweekend.I’msureyouwon’tregretit.,international,ReadthefollowingpassageandmarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.NewYorkiscalled“theBigApple”.Maybeitisnotexactlylikeanapple,it’scertainlyverybig.Therearetoomanypeople,that’stheproblem.Thestreetsarealwaysfullofcarsandtrucks;youcanneverfindaplacetopark.Travellingaroundisnevereasyinthecity.Ifyouhaveenoughmoney,youcantakeataxi.NewYorkcabsareyellow.Theylookallthesame.Butthedriversareverydifferent.SomewerebornandraisedinNewYork,butmanyarenewcomerstotheUnitedStates.Afewdriveslowly,butmostgoveryfast.Cabdrivingisadifficultjob.Itcanbedangerous,too.Thievesoftentrytostealthedrivers’money.Driverssometimesgethurt.Ifyoudon’twanttotakeataxi,youcangobybusoryoucantakethesubway.Thesubwayisquickandit’scheap,butsomeofitspartsareoldanddirty.Lightsdon’talwaysworkandthereareoftenfiresonthetrack.Onsomesubwaylines,therearenew,cleanandsilvertrains.Butyoucan’tseethecoloroftheoldtrainseasily.Thereistoomuchdirtandtoomuchgraffiti,insideandoutside.Whatdoes“acab”mean?,ataxi,MarkletterA,B,DorDonyouranswersheettoindicatetheunderlinedpartthatneedscorrectionineachofthefollowingquestions.MyteachersaidIcantalktoheraboutmyprojectanytime.,cantalk,MarkletterA,B,CorDonyouranswersheettoindicatethewordthatdiffersfromtheotherthreeinthepositionofprimarystressineachofthefollowingquestions.,habit,MarkletterA,B,CorDonyouranswersheettoindicatethebestsentencethatcanbemadefromthecuesgiven.I/not/know/what/do/make/mother/happy/.,Idon’tknowwhattodotomakemymotherhappy.,ReadthefollowingtextandmarktheletterA,B,CorDonyouranswertoindicatethecorrectwordthatbestfitsblank(27).Located(23)_______GiaoThuydistrict,theCountrysideMuseum(24)_______apopularattractionforvisitorstoNamDinhProvince.Themuseumwasestablishedbyaretiredteacher,Mrs.Khieu,whileworkingasateacher,sheliked(25)_______householdutensilsofresidentsintheTonkinregion.(26)_______the1990s,shehaspreservedobjectsthatpeople,particularfarmers,regularlyusedintheolddays,sothatyoungergenerationscanlearnabouttheseobjects.KnowingMrs.Khieu’sgood(27)_______,manypeoplehavebroughtherdailyusedsubjectsinruralareas,suchaswaterbuckets,differenttypesofbrooms,bronzeandwoodentraysandfishingbaskets.,intention,MarkletterA,B,CorDtoindicatethewordOPPOSITEinmeaningtotheunderlinedwordineachofthefollowingquestionsMymotheroftentellsmenevertoacceptaliftfromsomeoneI’vejustmet!,refuse,MarkletterA,B,DorDonyouranswersheettoindicatetheunderlinedpartthatneedscorrectionineachofthefollowingquestions.Iprefertalkingfacetofacetotalkinginthephone.,in,MarkletterA,B,CorDonyouranswersheettoindicatethesentencethatisclosestinmeaningtotheoriginalsentenceineachofthefollowingquestions.Iandidn’tknowhowtowater-ski,buthetriedtodoit.,AlthoughIandidn’tknowhowtowater-ski,hetriedtodoit.,MarkletterA,B,CorDonyouranswersheettoindicatethesentencethatisclosestinmeaningtotheoriginalsentenceineachofthefollowingquestions.Thepicnicwascancelledbecauseoftheheavyrain.,Butfortheheavyrain,thepicnicwouldn’thavebeencancelled.,MarkletterA,B,CorDonyouranswersheettoindicatethebestsentencethatcanbemadefromthecuesgiven.Nobody/can/deny/that/she/talent/arts/.,Nobodycandenythatshe’stalentedatarts.,ReadthefollowingtextandmarktheletterA,B,CorDonyouranswertoindicatethecorrectwordthatbestfitsblank(24).Located(23)_______GiaoThuydistrict,theCountrysideMuseum(24)_______apopularattractionforvisitorstoNamDinhProvince.Themuseumwasestablishedbyaretiredteacher,Mrs.Khieu,whileworkingasateacher,sheliked(25)_______householdutensilsofresidentsintheTonkinregion.(26)_______the1990s,shehaspreservedobjectsthatpeople,particularfarmers,regularlyusedintheolddays,sothatyoungergenerationscanlearnabouttheseobjects.KnowingMrs.Khieu’sgood(27)_______,manypeoplehavebroughtherdailyusedsubjectsinruralareas,suchaswaterbuckets,differenttypesofbrooms,bronzeandwoodentraysandfishingbaskets.,is,MarkletterA,B,CorDonyouranswersheettoindicatethebestsentencethatcanbemadefromthecuesgiven.many/place/theworld/,/people/used/dye/cloth/nature/material/.,Inmanyplacesintheworld,peopleusedtodyeclothwithnaturalmaterials.,MarkletterA,B,CorDonyouranswersheettoindicatethesentencethatisclosestinmeaningtotheoriginalsentenceineachofthefollowingquestions.“IfIwereyou,Iwouldtakeabreak,”TomsaidtoDaisy.,TomadvisedDaisytotakeabreak.,ReadthefollowingpassageandmarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.NewYorkiscalled“theBigApple”.Maybeitisnotexactlylikeanapple,it’scertainlyverybig.Therearetoomanypeople,that’stheproblem.Thestreetsarealwaysfullofcarsandtrucks;youcanneverfindaplacetopark.Travellingaroundisnevereasyinthecity.Ifyouhaveenoughmoney,youcantakeataxi.NewYorkcabsareyellow.Theylookallthesame.Butthedriversareverydifferent.SomewerebornandraisedinNewYork,butmanyarenewcomerstotheUnitedStates.Afewdriveslowly,butmostgoveryfast.Cabdrivingisadifficultjob.Itcanbedangerous,too.Thievesoftentrytostealthedrivers’money.Driverssometimesgethurt.Ifyoudon’twanttotakeataxi,youcangobybusoryoucantakethesubway.Thesubwayisquickandit’scheap,butsomeofitspartsareoldanddirty.Lightsdon’talwaysworkandthereareoftenfiresonthetrack.Onsomesubwaylines,therearenew,cleanandsilvertrains.Butyoucan’tseethecoloroftheoldtrainseasily.Thereistoomuchdirtandtoomuchgraffiti,insideandoutsideTheword“subway”canbereplacedby____.,Underground,MarkletterA,B,CorDonyouranswersheettoindicatethewordwhoseunderlinedpartdiffersfromtheotherthreeinpronunciationineachofthefollowingquestions.,relaxed,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.______________ourschoolissmall,ithasstrictrules.,Although,MarkletterA,B,CorDonyouranswersheettoindicatethewordCLOSESTinmeaningtotheunderlinedwordineachofthefollowingquestions.TheInternetisavailableincitiesandtowns,sowecannoteasilygetaccesstoitinthecountryside.,existing,ReadthefollowingpassageandmarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.NewYorkiscalled“theBigApple”.Maybeitisnotexactlylikeanapple,it’scertainlyverybig.Therearetoomanypeople,that’stheproblem.Thestreetsarealwaysfullofcarsandtrucks;youcanneverfindaplacetopark.Travellingaroundisnevereasyinthecity.Ifyouhaveenoughmoney,youcantakeataxi.NewYorkcabsareyellow.Theylookallthesame.Butthedriversareverydifferent.SomewerebornandraisedinNewYork,butmanyarenewcomerstotheUnitedStates.Afewdriveslowly,butmostgoveryfast.Cabdrivingisadifficultjob.Itcanbedangerous,too.Thievesoftentrytostealthedrivers’money.Driverssometimesgethurt.Ifyoudon’twanttotakeataxi,youcangobybusoryoucantakethesubway.Thesubwayisquickandit’scheap,butsomeofitspartsareoldanddirty.Lightsdon’talwaysworkandthereareoftenfiresonthetrack.Onsomesubwaylines,therearenew,cleanandsilvertrains.Butyoucan’tseethecoloroftheoldtrainseasily.Thereistoomuchdirtandtoomuchgraffiti,insideandoutside.WhatistheprobleminNewYork?,Itistoocrowded.,MarkletterA,B,CorDonyouranswersheettoindicatethesentencethatisclosestinmeaningtotheoriginalsentenceineachofthefollowingquestions.IwishIdidn’thavetogetupearlytomorrow.,Ihavetogetupearlytomorrow.,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.Sheisatalented______________.Hersongsarewidelylistenedtobyyoungpeople.,musician,MarkletterA,B,CorDonyouranswersheettoindicatethemostsuitableresponsetocompleteeachofthefollowingconversations.-“Ihaveboughtyouatoy.Happybirthdaytoyou!”-“_____________”,Whatalovelytoy!Thanks.,MarkletterA,B,CorDonyouranswersheettoindicatethewordwhoseunderlinedpartdiffersfromtheotherthreeinpronunciationineachofthefollowingquestions.,face,MarkletterA,B,DorDonyouranswersheettoindicatetheunderlinedpartthatneedscorrectionineachofthefollowingquestions.Minhisinterestedinbasketball,butheisn’tenoughtall.,enoughtall,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.Thechildren______________myhomevillageusedtogobarefoot,eveninwinter.Nowtheyallhaveshoes.,in,MarkletterA,B,CorDonyouranswersheettoindicatethemostsuitableresponsetocompleteeachofthefollowingconversations.Mom:“Don’tstayuplate,oryou’llbeexhaustedthenextday.”Mary:“___________”,No,Iwon’t.,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.Weallwishthere________________asmartboardinourclassroomnow.,were,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.Everycountryhasitsowncustomsand________________,traditions,MarkletterA,B,CorDonyouranswersheettoindicatethewordCLOSESTinmeaningtotheunderlinedwordineachofthefollowingquestions.Shecouldbeinanawfulmoodandrefusetoanswermyquestions.,bad,ReadthefollowingpassageandmarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.NewYorkiscalled“theBigApple”.Maybeitisnotexactlylikeanapple,it’scertainlyverybig.Therearetoomanypeople,that’stheproblem.Thestreetsarealwaysfullofcarsandtrucks;youcanneverfindaplacetopark.Travellingaroundisnevereasyinthecity.Ifyouhaveenoughmoney,youcantakeataxi.NewYorkcabsareyellow.Theylookallthesame.Butthedriversareverydifferent.SomewerebornandraisedinNewYork,butmanyarenewcomerstotheUnitedStates.Afewdriveslowly,butmostgoveryfast.Cabdrivingisadifficultjob.Itcanbedangerous,too.Thievesoftentrytostealthedrivers’money.Driverssometimesgethurt.Ifyoudon’twanttotakeataxi,youcangobybusoryoucantakethesubway.Thesubwayisquickandit’scheap,butsomeofitspartsareoldanddirty.Lightsdon’talwaysworkandthereareoftenfiresonthetrack.Onsomesubwaylines,therearenew,cleanandsilvertrains.Butyoucan’tseethecoloroftheoldtrainseasily.Thereistoomuchdirtandtoomuchgraffiti,insideandoutside.CabdriversinNewYork_____.,canbeattackedbythieves,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.Iused________________toschoolbutnowIcycletoschool.,towalk,MarkletterA,B,CorDonyouranswersheettoindicatethewordthatdiffersfromtheotherthreeinthepositionofprimarystressineachofthefollowingquestions.,wonderful,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.Shehasfailedherdrivingtestthreetimes.Shefeels________________,depressed,ReadthefollowingtextandmarktheletterA,B,CorDonyouranswertoindicatethecorrectwordthatbestfitsblank(26).Located(23)_______GiaoThuydistrict,theCountrysideMuseum(24)_______apopularattractionforvisitorstoNamDinhProvince.Themuseumwasestablishedbyaretiredteacher,Mrs.Khieu,whileworkingasateacher,sheliked(25)_______householdutensilsofresidentsintheTonkinregion.(26)_______the1990s,shehaspreservedobjectsthatpeople,particularfarmers,regularlyusedintheolddays,sothatyoungergenerationscanlearnabouttheseobjects.KnowingMrs.Khieu’sgood(27)_______,manypeoplehavebroughtherdailyusedsubjectsinruralareas,suchaswaterbuckets,differenttypesofbrooms,bronzeandwoodentraysandfishingbaskets.,Since,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.TheInternetisavast_______________ofcomputers,allconnectedtogether.,network,ReadthefollowingtextandmarktheletterA,B,CorDonyouranswertoindicatethecorrectwordthatbestfitsblank(25).Located(23)_______GiaoThuydistrict,theCountrysideMuseum(24)_______apopularattractionforvisitorstoNamDinhProvince.Themuseumwasestablishedbyaretiredteacher,Mrs.Khieu,whileworkingasateacher,sheliked(25)_______householdutensilsofresidentsintheTonkinregion.(26)_______the1990s,shehaspreservedobjectsthatpeople,particularfarmers,regularlyusedintheolddays,sothatyoungergenerationscanlearnabouttheseobjects.KnowingMrs.Khieu’sgood(27)_______,manypeoplehavebroughtherdailyusedsubjectsinruralareas,suchaswaterbuckets,differenttypesofbrooms,bronzeandwoodentraysandfishingbaskets.,collecting,MarkletterA,B,CorDonyouranswersheettoindicatethecorrectanswertoeachofthefollowingquestions.Thechildrenstartedto______________eachpartofthestory.,actout

**Comment by LetterC67** [comment]
Key này không phải nhé!

**Comment by paphananh** [comment]
Vậy key nào vậy bạn? (key trên mình lấy bằng GetCorrectAnswers.js)

**Comment by LetterC67** [comment]
> Vậy key nào vậy bạn? (key trên mình lấy bằng GetCorrectAnswers.js)

GetCorrectAnswers.js đang lỗi nên key lấy ra bị sai. Bạn đợi chút nữa lấy lại key là ok nhé!

**Comment by paphananh** [comment]
Ok bạn! Btw cho mình hỏi bạn học code ở đâu vậy?

**Comment by LetterC67** [comment]
> Ok bạn! Btw cho mình hỏi bạn học code ở đâu vậy?

Mình tự học thôi

**Comment by paphananh** [comment]
> Mình tự học thôi

Bạn có thể chia sẻ với mình giáo trình bạn học được k?

**Comment by LetterC67** [comment]
Mình học C/C++ trước, bạn lên mạng xem nhiều lắm, sau đó làm các bài tập vận dụng. Cứ học và làm nhiều rồi sẽ quen
