### ISSUE TITLE
Lấy đáp án của những bài đã làm từ tháng 4 trở về trước

### ISSUE THREAD

**Issue by paphananh** [LetterC67/Cheat-study.hanoi.edu.vn#56]
Bạn ơi, nếu mình có bài đã làm từ tháng 4 trở về trước mà bây giờ muốn lấy đáp án thì làm kiểu gì?
(GetCorrectAnswers.js k hoạt động)

**Comment by LetterC67** [comment]
Những bài đã làm từ lâu rồi thì hệ thống không lưu lại dữ liệu trên máy chủ nên không lấy được đâu nhé! Chỉ có làm lại thôi bạn!
