### ISSUE TITLE
Đây có phải là Red Queen bên codefun không :v

### ISSUE THREAD

**Issue by autongucode** [LetterC67/Cheat-study.hanoi.edu.vn#60]
Mình khá là ngưỡng mộ thành tích của bạn :))))

**Comment by LetterC67** [comment]
Sao bạn biết vậy 😅

**Comment by autongucode** [comment]
Mình cũng ở bên codefun, mới lên tím thấy bạn pro vjp :)))))

**Comment by LetterC67** [comment]
Bạn học KHTN à ?

**Comment by autongucode** [comment]
yep đúng rồi =)) bên 10A2Tin

**Comment by LetterC67** [comment]
Thế thì mình suýt cùng trường lol 😂

**Comment by autongucode** [comment]
thiếu điểm nhỉ ::) cay thật

**Comment by LetterC67** [comment]
Nah nếu bạn có danh sách Tin 1 cũ thì có tên mình ở trong đó :v

**Comment by autongucode** [comment]
ò vây ban chuyển trường

**Comment by LetterC67** [comment]
Yah mình chuyển sang ams 😅😅

**Comment by autongucode** [comment]
uầy tin ams thấy cũng có codefun đổ bộ nhưng cũng vì bạn đã đỏ rồi nên sang codeforce là vừa :)))
